### ISSUE TITLE
error when server goes offline

### ISSUE THREAD

**Issue by TechnoTyg** [AoElite/AutoReconnect#18]
Greetings! I installed this plugin, set everything up, and tested it. But when the server goes offline, the plugin is stuck at "reconnecting..." and gives the following error in the bungeecord console:
01:48:21 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4e70a728, id=11, owner=me.aoelite.bungee.autoreconnect.AutoReconnect@5990e6c5, task=me.aoelite.bungee.autoreconnect.ReconnectTask$2@5bd23f23, delay=1000, period=0, running=true) encountered an exception
java.lang.NoSuchFieldError: workerEventLoopGroup
    at me.aoelite.bungee.autoreconnect.ReconnectTask.ping(ReconnectTask.java:270)
    at me.aoelite.bungee.autoreconnect.ReconnectTask.tryReconnect(ReconnectTask.java:179)
    at me.aoelite.bungee.autoreconnect.ReconnectTask$2.run(ReconnectTask.java:95)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

then when I leave, it says:
01:50:32 [INFO] [TechnoTyg] -> UpstreamBridge has disconnected
01:50:34 [INFO] [/MY.IP.IS.HERE] <-> InitialHandler has pinged

did I set something up wrong or...? Thanks in advance.

**Comment by PseudoResonance** [comment]
https://github.com/AoElite/AutoReconnect/pull/19

This new update should solve it. Here is the jar file, it will be on SpigotMC soon though.
[AutoReconnect-1.6.3.jar.zip](https://github.com/AoElite/AutoReconnect/files/5420597/AutoReconnect-1.6.3.jar.zip)

**Comment by TechnoTyg** [comment]
Yes it's solved now. Thanks for the quick reply and fix! This is the best bungeecord plugin i've seen so far, i'm going to give this a 5 star review on spigotMC. Have a amazing day and keep up the amazing work! :)
