### ISSUE TITLE
Error loading plugin autoreconnect

### ISSUE THREAD

**Issue by giancrack782** [AoElite/AutoReconnect#29]
[WARNING] Error loading plugin AutoReconnect
java.lang.UnsupportedClassVersionError: me/aoelite/bungee/autoreconnect/AutoReconnect has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:340)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by PseudoResonance** [comment]
Sorry, I don't support the use of Java 8 anymore. Please update your server to use a more modern version of Java.
You can download the Java 11 build of this plugin [here](https://github.com/AoElite/AutoReconnect/files/6709274/Artifacts.zip) if you don't want to use Java 16:
