### ISSUE TITLE
AutoReconnect does have java 8 support?

### ISSUE THREAD

**Issue by ArefyNetwork** [AoElite/AutoReconnect#34]
Hey, we're using java 8 as most of the plugin are written here, but with latest version of autoreconnect it's giving me that issue:

`[09:42:27] [main/WARN]: Error loading plugin AutoReconnect
java.lang.UnsupportedClassVersionError: me/aoelite/bungee/autoreconnect/AutoReconnect has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_265]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_265]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_265]
	at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_265]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_265]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:435) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:341) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:7912bef:unknown]`

Would appreciate a lot if you could fix that, thanks!

**Comment by PseudoResonance** [comment]
Java 8 support should end in less than a year, in March 2022 and will be 8 years old, so I've dropped support for it. While BungeeCord itself has a minimum of Java 8, that will likely change to either Java 11 LTS or Java 17 LTS sometime soon, as Minecraft itself has moved to Java 16. As such, I decided to just drop Java 8, as I am using Java 11 features in the upcoming update.

Either way, from what I've seen, newer Java versions will provide minor performance benefits to BungeeCord, so it's worth updating to at least Java 11, and preferably Java 16. Version 1.6.6 can be built on Java 8 though. Here's probably the last version of this plugin for Java 8 though.

[AutoReconnect-1.6.6.jar.zip](https://github.com/AoElite/AutoReconnect/files/6974883/AutoReconnect-1.6.6.jar.zip)

**Comment by PseudoResonance** [comment]
Just thought I would confirm, version 1.6.6 is indeed the last version to run on Java 8. Version 2.0.0 and above will require Java 11 or higher.

**Comment by ArefyNetwork** [comment]
Hello, we updated to Java 16. Where can i get version 2.0.0?

thanks

**Comment by PseudoResonance** [comment]
Update 1.6.7 should be working on Minecraft 1.18
[AutoReconnect-1.6.7.jar.zip](https://github.com/AoElite/AutoReconnect/files/7867267/AutoReconnect-1.6.7.jar.zip)
.
