### ISSUE TITLE
The plugin does not load

### ISSUE THREAD

**Issue by francis12cy** [AoElite/AutoReconnect#36]
This is what the spigot server console gives me when I turn on the server (I'm using version 1.6.6):

[01:00:09] [Server thread/WARN]: Legacy plugin AutoReconnect v1.6.6 does not specify an api-version.
[01:00:09] [Server thread/ERROR]: Could not load 'plugins\AutoReconnect-1.6.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:400) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:891) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.Bukkit.reload(Bukkit.java:675) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:776) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:761) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:475) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:439) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/plugin/Plugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:188) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.plugin.Plugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:142) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:188) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-1.17.1.jar:3221-Spigot-b166a49-18027d0]
        ... 15 more

**Comment by PseudoResonance** [comment]
This is a BungeeCord plugin, not a Bukkit/Spigot plugin. Please install this plugin to your BungeeCord server instead.

If you're running just a single Bukkit/Spigot server, you can always make another BungeeCord server just to use this plugin I guess.
