### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mrboog12** [AoElite/AutoReconnect#37]
18.01 02:02:01 [Server] INFO [Reconnect] DownstreamInboundHandler@63c023bb:183 HANDLE_EXCEPTION
18.01 02:02:01 [Server] INFO io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 304))
18.01 02:02:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at java.lang.Thread.run(Thread.java:831) [?:?]
18.01 02:02:01 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 304))
18.01 02:02:01 [Server] INFO at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:139) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:129) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:35) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[bungeecord-1.18.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616]
18.01 02:02:01 [Server] INFO ... 22 more

Caused when I click on an armor stand (usually rapid click), triggers this in the console

**Comment by PseudoResonance** [comment]
Have you tested without AutoReconnect installed? I see no mention of the plugin in the logs.

Also, when posting logs, please put them inside a code block to make it easier to read. It should be typed like this:
````
```
logs
```
````
